In [1]:
import tensorflow as tf

try:
    from  DataObtainer import get_train_test_vectors_from_ptb_file
except:
    from .DataObtainer import get_train_test_vectors_from_ptb_file
%load_ext autoreload

In [22]:
filename = '../data/ptb.test.txt'
hidden_size = 100

In [23]:
hidden_size = 100
train_x, train_y, test_x, test_y, vocabulary_size, train_x_seq, train_y_seq, test_x_seq, test_y_seq \
    = get_train_test_data(filename, 10 ** 3, embedding_size=hidden_size)

lstm = LSTMSingleLayer(hidden_size=hidden_size, vocab_size=vocabulary_size)
ph_x = tf.placeholder(dtype=tf.float32, shape=[1, hidden_size], name="X")
lstm.train(ph_x, train_x_seq)

NameError: name 'get_train_test_data' is not defined

In [6]:
train_vectors

<tf.Tensor 'embedding_lookup:0' shape=(57701, 100) dtype=float32>

In [16]:
class LSTMSingleLayer():
    def __init__(self, hidden_size):
        self.hidden_size = hidden_size
        self.model = tf.nn.rnn_cell.BasicLSTMCell(hidden_size, state_is_tuple=True)
        self.state = self.model.zero_state(batch_size=1, dtype=tf.float32)

In [17]:
m = LSTMSingleLayer(10)

In [19]:
m.model(inputs=)

TypeError: 'LSTMSingleLayer' object is not callable

In [36]:
l = [6,5,1]
o = tf.one_hot(indices=l, depth=7)

In [37]:
with tf.Session() as s:
    print(s.run(o))

[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]]


In [2]:
import numpy as np

In [3]:
a = tf.Variable(initial_value=np.random.randn(5,3))

In [5]:
a.get_shape()

TensorShape([Dimension(5), Dimension(3)])

In [10]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    print(s.run(a))

[[ 1.01305551  0.36671423  0.33950013]
 [-1.47441396 -0.11074149 -0.53360861]
 [ 0.92909177 -0.55157479 -0.64794466]
 [ 0.44147145  0.94336165 -0.28318978]
 [-0.65006925  0.63561692 -0.48137205]]


In [11]:
seq = tf.Variable(initial_value=[i for i in range(20)])

In [13]:
seq

In [20]:
seq2 = tf.reshape(tensor=seq, shape=[-1])

In [30]:
seq3 = tf.reshape(seq, [1,-1])

In [21]:
seq2

<tf.Tensor 'Reshape_1:0' shape=(20,) dtype=int32>

In [22]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    print(s.run(seq2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [23]:
def tfprint(a):
    with tf.Session() as s:
        s.run(tf.global_variables_initializer())
        print(s.run(a))

In [24]:
tfprint(seq2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
tf.size(seq2)

<tf.Tensor 'Size:0' shape=() dtype=int32>

In [32]:
tfprint(tf.shape(seq3))

[ 1 20]
