In [1]:
import tensorflow as tf
import numpy as np
import sys
%pylab inline
%load_ext autoreload
%autoreload 2
sys.path.insert(0,'../streampredictor/')

Populating the interactive namespace from numpy and matplotlib


In [2]:
def tfprint(a):
    with tf.Session() as s:
        s.run(tf.global_variables_initializer())
        print(s.run(a))

In [3]:
seq = tf.Variable(initial_value=np.array(range(20)))
seq

In [4]:
tfprint(seq)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
tfprint(tf.shape(seq))

[20]


In [6]:
batch_size = 2
time_step = 3

In [7]:
data_len = tf.size(seq)

In [8]:
tfprint(data_len)

20


In [9]:
batch_len = data_len//batch_size
tfprint(batch_len)

10


In [10]:
data = tf.reshape(seq[0:batch_size*batch_len], [batch_size, batch_len])
data

<tf.Tensor 'Reshape:0' shape=(2, ?) dtype=int32>

In [11]:
tfprint(data)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [12]:
epoch_size = (batch_len-1)//time_step
epoch_size

<tf.Tensor 'floordiv_1:0' shape=() dtype=int32>

In [13]:
tfprint(epoch_size)

3


In [14]:
i = tf.train.range_input_producer(epoch_size, shuffle=False).dequeue()
i

<tf.Tensor 'fraction_of_32_full_Dequeue:0' shape=() dtype=int32>

In [15]:
fs = tf.slice(data, [0, 2], [batch_size,time_step])
tfprint(fs)
fs

[[ 2  3  4]
 [12 13 14]]


<tf.Tensor 'Slice:0' shape=(2, 3) dtype=int32>

In [16]:
from tensorflow.models.rnn.ptb import reader


In [17]:
X, Y = reader.ptb_producer(seq, batch_size=batch_size, num_steps=time_step)

In [18]:
X.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [ ]:
tfprint(tf.reshape(X, [-1]))